[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_404 = "Gv6gE629wMtPRAL8NnQixPFXK18WCuyxMEjvgfeHwMeC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zhoujianing/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


# [test]
# startup_wait = 5000
# shutdown_wait = 2000

# [test.validator]
# bind_address = "127.0.0.1"
# url = "https://api.mainnet-beta.solana.com"
# ledger = ".anchor/test-ledger"
# rpc_port = 8899

# [[test.validator.clone]]
# address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"